name: Deploy to Google Cloud Run using Artifact Registry

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ./src/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        working-directory: ./src/frontend
        run: npm install

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker us-south1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="us-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gin-rummy/frontend/nextjs-app:${{ github.sha }}"
          docker build -t $IMAGE_NAME ./src/frontend
          docker push $IMAGE_NAME

      - name: Deploy to Google Cloud Run
        id: deploy
        run: |
          gcloud run deploy gin-rummy-frontend \
            --image us-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gin-rummy/frontend/nextjs-app:${{ github.sha }} \
            --platform managed \
            --region us-south1 \
            --allow-unauthenticated \
            --port 3000 \
            --memory 3Gi \
            --cpu 2
          echo "SERVICE_URL=$(gcloud run services describe gin-rummy-frontend --region us-south1 --format 'value(status.url)')" >> $GITHUB_ENV

      - name: Output Service URL
        run: |
          echo "Deployed service URL: ${{ env.SERVICE_URL }}"
